"""Earlier L0 releases of the old-name answer templates retire like the canonical bytes."""
from __future__ import annotations

import contextlib
import hashlib
import io
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts/lib"))
import l1_answer_template_upgrade as upgrade  # noqa: E402
import l1_template_ownership as ownership  # noqa: E402

# Exact bytes L0 shipped under copier/<name>/.copier-answers.yml.j2 before cf99c27 (blobs
# 87895f112969 and 0cbd996b4d29); healthco, holdingco and teachingco still carry them.
LEGACY_BYTES = {
    "tpl-monorepo": (
        "# Generated by Copier. Keep committed for reproducibility.\n"
        "company_slug: '{{ company_slug }}'\ncompany_name: '{{ company_name }}'\n"
        "repo_slug: '{{ repo_slug }}'\npackage_manager: '{{ package_manager }}'\n"
        "enable_community_pack: {{ enable_community_pack | lower }}\n"
        "enable_release_pack: {{ enable_release_pack | lower }}\n"
        "enable_vouch_gate: {{ enable_vouch_gate | lower }}\n"
        "kernel_ontology_ref: '{{ kernel_ontology_ref }}'\ncompany_ontology_ref: '{{ company_ontology_ref }}'\n"
        "core_owner_handle: '{{ core_owner_handle }}'\norg_owner_handle: '{{ org_owner_handle }}'\n"
        "project_owner_handle: '{{ project_owner_handle }}'\n"
        "template_source_sha: '{{ template_source_sha | default(\"unknown\") }}'\n"
    ),
    "tpl-package": (
        "# Generated by Copier. Keep committed for reproducibility.\n"
        "company_slug: '{{ company_slug }}'\ncompany_name: '{{ company_name }}'\n"
        "package_name: '{{ package_name }}'\npackage_type: '{{ package_type }}'\n"
        "language: '{{ language }}'\npackage_description: '{{ package_description | default(\"\") }}'\n"
        "kernel_ontology_ref: '{{ kernel_ontology_ref }}'\ncompany_ontology_ref: '{{ company_ontology_ref }}'\n"
    ),
}
TEMPLATE = {"template": ["copier/**"], "agent": []}


def canonical_bytes(name: str) -> bytes:
    return (ROOT / "copier-template/copier" / name / upgrade.SOURCE).read_bytes()


def git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@x", "-c", "core.hooksPath=/dev/null",
                    "-C", str(repo), *args], check=True, capture_output=True, env={"PATH": "/usr/bin:/bin"})


class LegacyDigestTests(unittest.TestCase):
    def test_legacy_constants_are_the_shipped_bytes_and_successors_stay_canonical(self) -> None:
        for name, text in LEGACY_BYTES.items():
            digest = hashlib.sha256(text.encode()).hexdigest()
            self.assertEqual(upgrade.LEGACY[name], (digest,))
            self.assertEqual(upgrade.accepted(name), (upgrade.APPROVED[name], digest))
            self.assertEqual(hashlib.sha256(canonical_bytes(name)).hexdigest(), upgrade.APPROVED[name])

    def plan_repo(self, root: Path, name: str, old: bytes, successor: bytes) -> tuple[Path, Path]:
        repo, incoming = root / "repo", root / "incoming"
        (repo / "copier" / name).mkdir(parents=True)
        (repo / "copier" / name / upgrade.OLD).write_bytes(old)
        git(repo, "init", "-q")
        git(repo, "add", ".")
        git(repo, "commit", "-qm", "base")
        (incoming / "copier" / name).mkdir(parents=True)
        (incoming / "copier" / name / upgrade.NEW).write_bytes(successor)
        return repo, incoming

    def test_legacy_old_name_retires_with_a_canonical_successor(self) -> None:
        name = "tpl-monorepo"
        with tempfile.TemporaryDirectory() as td:
            repo, incoming = self.plan_repo(Path(td), name, LEGACY_BYTES[name].encode(), canonical_bytes(name))
            entries = upgrade.plan(repo, incoming, TEMPLATE, TEMPLATE, ownership.owner)
            old = f"copier/{name}/{upgrade.OLD}"
            self.assertEqual(list(entries), [old])
            self.assertEqual(entries[old]["record"]["sha256"], upgrade.LEGACY[name][0])
            upgrade.revalidate(repo, entries)

    def test_legacy_old_name_refuses_a_successor_that_is_not_canonical(self) -> None:
        name = "tpl-package"
        legacy = LEGACY_BYTES[name].encode()
        with tempfile.TemporaryDirectory() as td:
            repo, incoming = self.plan_repo(Path(td), name, legacy, legacy)
            with self.assertRaisesRegex(ValueError, "unapproved answer template"):
                upgrade.plan(repo, incoming, TEMPLATE, TEMPLATE, ownership.owner)

    def test_edited_old_name_bytes_are_still_refused(self) -> None:
        name = "tpl-monorepo"
        with tempfile.TemporaryDirectory() as td:
            edited = (LEGACY_BYTES[name] + "extra: '1'\n").encode()
            repo, incoming = self.plan_repo(Path(td), name, edited, canonical_bytes(name))
            with self.assertRaisesRegex(ValueError, "modified or unapproved answer template"):
                upgrade.plan(repo, incoming, TEMPLATE, TEMPLATE, ownership.owner)


class ShowDiffTests(unittest.TestCase):
    def test_missing_final_newline_is_marked_so_the_next_plan_line_starts_clean(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            old, new = Path(td) / "old", Path(td) / "new"
            old.write_text("a\nb")
            new.write_text("a\nb\nc")
            out = io.StringIO()
            with contextlib.redirect_stdout(out):
                ownership.show_diff("f", old, new)
                print("update: next")
            lines = out.getvalue().splitlines()
            self.assertEqual(lines[-1], "update: next")
            self.assertIn("\\ No newline at end of file", lines)


if __name__ == "__main__":
    unittest.main()
