#!/usr/bin/env sh
set -eu
repo_root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$repo_root"
. "$repo_root/tests/ci_guardrails_helpers.sh"
. "$repo_root/tests/ci_guardrails_context.sh"
. "$repo_root/tests/ci_guardrails_root.sh"
sh "$repo_root/tests/ci_unittest.sh" guardrails-main pinned tests.test_ci_profile tests.test_hosted_ci tests.test_ci_red_green tests.test_l1_template_transitions tests.test_l1_template_company_ownership.CompanyOntologyTests.test_legacy_plans_stay_nonempty_and_map_v2_refuses_unknown_or_overlapping_classes tests.test_company_ontology_ref_inheritance tests.test_l2_template_source tests.test_l1_answer_template_upgrade.UpgradeSafetyTests tests.test_l1_answer_template_legacy tests.test_l1_template_gitlink_retirements >/dev/null || fail "L1 transition / company ontology upgrade / gitlink and retirement behavior tests failed"
sh "$repo_root/tests/ci_unittest.sh" guardrails-generation-units pinned-9.11.1 tests.test_ci_generation_units >/dev/null || fail "generation unit seam contracts failed"
sh "$repo_root/tests/ci_unittest.sh" guardrails-ci-planning pinned-9.11.1 tests.test_ci_coverage tests.test_ci_schedule >/dev/null || fail "independent coverage and routing contracts failed"
sh "$repo_root/tests/ci_unittest.sh" guardrails-ci-static pinned-9.11.1 tests.test_ci_guardrails >/dev/null || fail "static guardrail seam contracts failed"
sh "$repo_root/tests/ci_unittest.sh" guardrails-ci-candidate pinned-9.11.1 tests.test_ci_worker tests.test_ci_aggregate tests.test_ci_candidate_workflow >/dev/null || fail "candidate execution contracts failed"
. "$repo_root/tests/ci_guardrails_l2.sh"
sh "$repo_root/tests/ci_unittest.sh" guardrails-system4d pinned tests.test_l2_system4d_context >/dev/null || fail "L2 system4d.yaml context tests failed"
. "$repo_root/tests/ci_guardrails_tail.sh"
